USE mysqlvs;
CREATE TABLE IF NOT EXISTS mysqlvs.TBL_MEMBER (
    MEMNO       BIGINT          AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MEMID       VARCHAR(20)     NOT NULL,
    MEMPW       VARCHAR(100)    NOT NULL,
    MEMNICK     VARCHAR(30)     UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mysqlvs.TBL_ROLE (
    ROLENO      INT         PRIMARY KEY NOT NULL,
    ROLENAME    VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mysqlvs.TBL_MEMBER_ROLE (
    MEMNO       BIGINT  NOT NULL,
    ROLENO      INT     NOT NULL,
    FOREIGN KEY (MEMNO)  REFERENCES TBL_MEMBER (MEMNO),
    FOREIGN KEY (ROLENO) REFERENCES TBL_ROLE (ROLENO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mysqlvs.TBL_BOARD (
    NO         BIGINT           PRIMARY KEY AUTO_INCREMENT,
    TITLE      VARCHAR(100)     NOT NULL,
    CONTENTS   TEXT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TBL_ROLE (ROLENO, roleName) VALUES (1, 'ADMIN');
INSERT INTO TBL_ROLE (ROLENO, roleName) VALUES (2, 'USER');
